project:
  type: website
  output-dir: docs
  
website:
  title: "gabrielle jarrett"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/gabriellejarrett/gjwebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Gabrielle Jarrett"

format:
  html:
    theme: cerulean
    toc: true

editor: source

